_id: "387092920424988672"
name: "111"
description: "2222"
model: gpt-3.5-turbo
createdAt: 2023-12-05T04:09:04.068Z
updatedAt: 2023-12-05T04:11:34.642Z
createdBy: z1UxQ2a7Pe4UHpwaFzpwvfcTsestKfQ7ecJ
updatedBy: z1UxQ2a7Pe4UHpwaFzpwvfcTsestKfQ7ecJ
pinnedAt: null
icon: https://bbqazgzliugjem7aborajfbybadnh2zqtocze6dqgom.did.abtnet.io/image-bin/uploads/2c2e4ec3dcd579a662569430de26f56a.png
gitType: default
temperature: 1
topP: 1
presencePenalty: null
frequencyPenalty: null
maxTokens: null
gitAutoSync: true
gitLastSyncedAt: 2023-12-05T04:11:05.414Z
