gitType: default
temperature: 1
topP: 1
_id: "387092920424988672"
model: gpt-3.5-turbo
createdBy: z1UxQ2a7Pe4UHpwaFzpwvfcTsestKfQ7ecJ
updatedBy: z1UxQ2a7Pe4UHpwaFzpwvfcTsestKfQ7ecJ
icon: https://bbqazgzliugjem7aborajfbybadnh2zqtocze6dqgom.did.abtnet.io/image-bin/uploads/2c2e4ec3dcd579a662569430de26f56a.png
updatedAt: &a1 2023-12-05T04:09:04.068Z
createdAt: *a1
